logging:
  level:
    org:
      springframework:
        security:
        web: DEBUG
        org:hibernate: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 822218261122-6ja8rn0j65f2ubimo7qoqnq7s0es8s8j.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email